<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Train Details</title>
    <style>
        body { 
            font-family: 'Arial', sans-serif; 
            margin: 0; 
            padding: 0; 
            position: relative; 
            color: #333;
            background-color: #ffffff;
        }

        .container { 
            width: 96%; 
            max-width: 850px; 
            margin: 0 auto; 
            padding: 30px;
            padding-right: 1in; 
            padding-bottom: 0.2in;  /* Add 1-inch margin at the bottom */
            background-color: #ffffff; 
            position: relative;
            z-index: 1;
        }

        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 30px;
        }

        th, td { 
            border: 1px solid #ddd; 
            padding: 10px; 
            text-align: left; 
            font-size: 14px;
        }

        th { 
            background-color: #00796b; 
            color: white;
            font-weight: bold;
        }

        td {
            background-color: #e8f5e9;
        }

        .section { 
            margin-top: 30px; 
        }

        .title { 
            font-size: 20px; 
            font-weight: bold; 
            margin-bottom: 5px; 
            color: #00796b;
        }

        .timestamp { 
            text-align: right; 
            font-size: 12px; 
            color: #777; 
            margin-top: 10px; 
        }

        .header {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 30px;
            text-align: center;
        }

        .logo {
            width: 120px;
            height: auto;
            margin-right: 20px;
        }

        .heading {
            font-size: 36px;
            font-weight: bold;
            color: #00796b;
            letter-spacing: 1px;
        }

        .train-name {
            font-size: 24px;
            color: #00796b;
            font-weight: bold;
            text-align: center;
            margin-top: 20px;
        }

        .compartment-table th, .compartment-table td {
            font-size: 12px;
            text-align: center;
        }

        .compartment-table td {
            background-color: #f1f1f1;
        }

        .train-image {
            display: block;
            margin: 20px auto;
            border: 1px solid #ddd;
            padding: 5px;
            border-radius: 8px;
        }

        .line {
            border-top: 2px solid #00796b;
            margin-top: 20px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">

        <div class="timestamp">
            <strong>PDF Generated on:</strong> {{ now()->setTimezone('Asia/Dhaka')->format('d/m/Y h:i A') }}<br>
            <strong>PDF Generated by:</strong> {{ $admin->name ?? 'Unknown Admin' }}
        </div>

        <div class="header">
            <img src="{{ public_path('images/Trainlogo.png') }}" alt="Logo" class="logo">
            <div class="heading">Bangladesh Railway</div>
        </div>
        
        <h2 class="train-name">Train Details: {{ $train->trainname }}</h2>
        
        @if($train->train_image)
            <img src="{{ public_path('storage/' . $train->train_image) }}" alt="Train Image" class="train-image" width="250">
        @endif

        <div class="section">
            <div class="title" style="margin-bottom: 5px;">Basic Information</div>
            <table style="margin-top: 5px;">
                <tr>
                    <th>Train Name</th>
                    <th>Total Compartment</th>   
                </tr>
                <tr>
                    <td>{{ $train->trainname }}</td>
                    <td>{{ $train->compartmentnumber }}</td>
                </tr>
            </table>
            <div class="line"></div>
        </div>

        <div class="section">
            <div class="title" style="margin-bottom: 5px;">Compartments</div>
            <table class="compartment-table" style="margin-top: 5px;">
                <tr>
                    <th>Compartment Name</th>
                    <th>Type</th>
                    <th>Total Seats</th>
                    <th>Available Seats</th>
                    <th>Booked Seats</th>
                    <th>Price</th>
                </tr>
                @foreach($train->traincompartments as $compartment)
                <tr>
                    <td>{{ $compartment->compartmentname }}</td>
                    <td>{{ $compartment->compartmenttype ?? 'N/A' }}</td>
                    <td>{{ $compartment->total_seats }}</td>
                    <td>{{ $compartment->available_seats }}</td>
                    <td>{{ $compartment->booked_seats }}</td>
                    <td>{{ $compartment->price ? '$' . number_format($compartment->price, 2) : 'N/A' }}</td>
                </tr>
                @endforeach
            </table>
            <div class="line"></div>
        </div>

        <div class="section">
            <div class="title" style="margin-bottom: 5px;">Train Routes</div>
            <table style="margin-top: 5px;">
                <tr>
                    <th>Source</th>
                    <th>Destination</th>
                    <th>Departure Time</th>
                    <th>Arrival Time</th>
                    <th>Departure Date</th>
                    <th>Arrival Date</th>
                </tr>
                @foreach($train->trainupdowns as $updown)
                <tr>
                    <td>{{ $updown->tsource }}</td>
                    <td>{{ $updown->tdestination }}</td>
                    <td>{{ \Carbon\Carbon::parse($updown->tdeptime)->format('h:i A') }}</td>
                    <td>{{ \Carbon\Carbon::parse($updown->tarrtime)->format('h:i A') }}</td>
                    <td>{{ \Carbon\Carbon::parse($updown->tdepdate)->format('d/m/Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($updown->tarrdate)->format('d/m/Y') }}</td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</body>
</html>
